<?php
/**
 * Created by PhpStorm.
 * User: papa
 * Date: 31/03/2019
 * Time: 12:20 AM
 */
include_once ("../if/common.functions.php");
class clientes_model extends CommonFunctions
{
    private $id;
    private $nombre;
    private $telefono;
    private $direccion;
    private $codigoPostal;
    private $colonia;
    private $estado;
    private $municipio;
    private $personaContacto;
    private $email;
    private $status;


    public function new(
        $nombre,$telefono,$direccion,$codigoPostal,$colonia,$estado,$municipio,$personaContacto,$email,$status
    ){

        $this->nombre=$nombre;
        $this->telefono = $telefono;
        $this->direccion = $direccion;
        $this->codigoPostal = $codigoPostal;
        $this->colonia = $colonia;
        $this->estado = $estado;
        $this->municipio = $municipio;
        $this->personaContacto = $personaContacto;
        $this->email = $email;
        $this->status = $status;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    public function objectToArray(){
             $array = array(
                 "Id" => $this->id,
                 "Nombre" => $this->nombre,
                 "Telefono" => $this->telefono,
                 "Direccion" => $this->direccion,
                 "Codigo_Postal" => $this->codigoPostal,
                 "Colonia" => $this->colonia,
                 "Estado" => $this->estado,
                 "Municipio" => $this->municipio,
                 "Persona_Contacto" => $this->personaContacto,
                 "Email" => $this->email,
                 "Status" => $this->status
             );
             return $array;
    }

    public function objectToArrayInsert(){
        $array = array(
            ":nombre" => $this->nombre,
            ":telefono" => $this->telefono,
            ":direccion" => $this->direccion,
            ":codigoPostal" => $this->codigoPostal,
            ":personaContacto" => $this->personaContacto,
            ":email" => $this->email,
            ":status" => $this->status
        );
        return $array;
    }

    public function objectToJson($object)
    {
        return parent::objectToJson($object); // TODO: Change the autogenerated stub
    }

    public function getClienteJson(){
        return $this->objectToJson($this->objectToArray());
    }


}